### ISSUE TITLE
How to share Image + Text + URL via WhatsApp

### ISSUE THREAD

**Issue by owidat** [Telerik-Verified-Plugins/SocialSharing#1]
I'm using this plugin in my project with Cordova 3.0 and Telerik AppBilder, My application is targeting iOS and Android.

When the user select sharing via whatsapp, the only thing being share is the photo, is there any other solution to share (image, text and url) to whatsapp.

My code:

```
        window.plugins.socialsharing.share( 
        msg, 
        imgUrl, 
        url, 
        [function(result) {alert('success'); console.log(result)}], 
        [function(result) {alert('error'); console.log(result)}]);
```

Also when I use:

```
        window.plugins.socialsharing.shareViaWhatsApp( 
        msg, 
        imgUrl, 
        url, 
        [function(result) {alert('success'); console.log(result)}], 
        [function(result) {alert('error'); console.log(result)}]);
```
- is it a WhatsApp problem?

**Comment by derChristoph** [comment]
Super! funktioniert! vielleicht kannst du es ja mit aufnehmen!

**Comment by damianpumar** [comment]
Hi! use my Plugin! https://github.com/Damian-Pumar/Xamarin-Plugins

**Comment by ghost** [comment]
Hi Damian,
Do u have anything for sharing of (image + text) on whatsapp at the same time from another ios app(objective c or swift)?

**Comment by damianpumar** [comment]
Hi piyush-verma,
I created Android plugin to sharing image and text at the same time.

`void ShareImage(String urlImage, String pathToSave, String title, params String[] comments);`
[https://github.com/Damian-Pumar/Xamarin-Plugins/blob/master/UI.Droid/Plugin/ShareImageTask.cs](url)

I used Xamarin for develop this plugin, you can sharing image and text using url for the image.
Regards.

**Comment by keyurshah070** [comment]
@Damian-Pumar 

Do you have any solution to share image from web for PHP or any hint ?

Kindly looking forward for your response.

**Comment by gomathyfollowon** [comment]
Shall i know whatsapp share  dynamic image and text, is possible at mobile website, any updates? have the plug-in/functionalty to share the images on whatsapp?
#Damian-Pumar
thankyou

**Comment by sri94aa** [comment]
Hi, 

When I pass the URL as a parameter, I am getting it as a text only and not as an hyperlink. Can anyone tell me how to resolve it?

**Comment by amanbhk7** [comment]
However I'd like to share an image trough a button on my website like someone would share an image from his phone (gallery). Is this anyhow possible?
I know you can share messages with and this is **[working on android and ios now:](https://bynext.com/2017/01/27/send-image-hyperlink-whatsapp/)**
<a href="whatsapp://send?text=Hello world this is a message and a link http://www.example.com/image.jpg">Share with whatsapp</a>
