### ISSUE TITLE
Fails to build for Android

### ISSUE THREAD

**Issue by michaelhodgins** [Telerik-Verified-Plugins/SocialSharing#10]
Hi

I've just added this plugin to my Ionic project, and when I run `ionic run android` I get the following error.

:compileDebugJavaWithJavac/Users/michael/Developer/Projects/phonegap/initial/platforms/android/src/nl/xservices/plugins/SocialSharing.java:12: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/michael/Developer/Projects/phonegap/initial/platforms/android/src/nl/xservices/plugins/SocialSharing.java:392: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class SocialSharing
/Users/michael/Developer/Projects/phonegap/initial/platforms/android/src/nl/xservices/plugins/SocialSharing.java:405: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class SocialSharing

I've done a quick search on the web, and it looks like I'm missing annotations.jar, but I thought Gradle sorted out the dependencies, so I'm stuck.

**Comment by michaelhodgins** [comment]
So I'd installed the plugin by following the Telerik instructions, `cordova plugin add https://github.com/Telerik-Verified-Plugins/SocialSharing`.

I've now uninstalled this version, 5.0.11, and installed using the cordova instructions, `cordova plugin add cordova-plugin-x-socialsharing`, which installs 5.0.12.

Building for Android now completes correctly.

**Comment by EddyVerbruggen** [comment]
Yeah see my comment here: https://github.com/Telerik-Verified-Plugins/SocialSharing/pull/7

I will remove it.

**Comment by EddyVerbruggen** [comment]
It's perfectly fine to use `cordova plugin add cordova-plugin-x-socialsharing` as you're doing now, but if you have time please verify using `cordova plugin add https://github.com/Telerik-Verified-Plugins/SocialSharing` works correctly for you now as well.

**Comment by michaelhodgins** [comment]
Yes, it does work now.
