### ISSUE TITLE
IOS dialog not showing

### ISSUE THREAD

**Issue by flieks** [Telerik-Verified-Plugins/SocialSharing#11]
Hi,

Only when i press 2 times the home button, the dialog pops up (see img), and from then on the share button always works.
![image](https://cloud.githubusercontent.com/assets/5032389/15107044/a3428c90-15cd-11e6-8c06-0b7109676aa3.png)

What can i do?

Thanks

**Comment by EddyVerbruggen** [comment]
Crosspost of https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/595, handling there.
