### ISSUE TITLE
TypeError: window.plugins is undefined

### ISSUE THREAD

**Issue by diazpaul** [Telerik-Verified-Plugins/SocialSharing#12]
I installed this plugin by telerik platform, I don't know if it need more configuration. 
i just write this code : 

`<a href="#" class="icono-navbar" onclick="window.plugins.socialsharing.share('Message only')">
<i class="fa fa-share-alt" aria-hidden="true"></i>
</a>`

Regards

**Comment by EddyVerbruggen** [comment]
How are you running the app? Web, simulator, companion app, real device? And is this iOS or Android?

**Comment by diazpaul** [comment]
Hi, 
in web simulator and real device, Android.

**Comment by diazpaul** [comment]
Is there any way to solve it?

**Comment by EddyVerbruggen** [comment]
Share your entire `index.html` and I may take a look.

**Comment by diazpaul** [comment]
it's all in spanish

[index.txt](https://github.com/Telerik-Verified-Plugins/SocialSharing/files/309760/index.txt)

**Comment by EddyVerbruggen** [comment]
- That line `<script src="js/SocialSharing.js"></script>` should not be there.
- It doesn't work in a web browser
- Is `cordova.js` also available on your device?
- Is the plugin installed (how)?
- Do you build this with the Cordova CLI?
- .. share your project if you want more suggestions

**Comment by diazpaul** [comment]
This is the repository: 
[https://github.com/diazpaul/efecto_cocuyo_app](https://github.com/diazpaul/efecto_cocuyo_app)
i installed the plugin again, but now the error is this:
`Uncaught TypeError: Cannot read property 'socialsharing' of undefined`

**Comment by EddyVerbruggen** [comment]
i don't see SocialSharing in the [list of plugin in your project](https://github.com/diazpaul/efecto_cocuyo_app/blob/master/.abproject#L45-L64)

**Comment by diazpaul** [comment]
that's weird!, i reinstalled the plugin, then the error was other, `Uncaught TypeError: Cannot read property 'socialsharing' of undefined`, then i replaced `var cordova = require('cordova');` to `var cordova = window.cordova;` and it works now. Thanks for answer.

**Comment by praveen-vasudhaika** [comment]
@diazpaul, the same change worked for me as well!!
