### ISSUE TITLE
iOS 10 not working?

### ISSUE THREAD

**Issue by nprather** [Telerik-Verified-Plugins/SocialSharing#15]
I started using this plugin a couple years ago and it's been great.  Recently my users are reporting errors on iOS 10.  I'm going to update my code to use the latest version of this plugin to try to replicate the error.  

**Has anyone else had errors on iOS 10?**

Thanks,
Nathan

**Comment by RML-Admin** [comment]
Hi - I am seeing a problem with iOS 10.

Thanks
Santi

**Comment by EddyVerbruggen** [comment]
Is there a way to reproduce the problem?

**Comment by nprather** [comment]
Sorry, I think this was a problem on my end...
