### ISSUE TITLE
shareViaWhatsapp behaviour is incorrect when using img on iOS 9.0.2

### ISSUE THREAD

**Issue by andreground** [Telerik-Verified-Plugins/SocialSharing#4]
Hi!

I'm implementing share via whatsapp in my app and according to reference I'm adding it this way:

$cordovaSocialSharing
                         .shareViaWhatsApp(null,'www/img/test.png', null)
                         .then(function(result) {
                               console.log("WHATSHAPP SHARE OK");
                               // Success!
                               }, function(err) {
                               // An error occurred. Show a message to the user
                               console.log("WHATSHAPP SHARE ERROR");
                               });

It happens that if I share just text (like shareViaWhatsApp('hello', null, null)), everything works fine; whatsapp gets opened right away. When sharing an image ONLY (like in the code example I pasted) the share sheet gets fired instead of moving directly to whatsapp.

Is this an expected behaviour? I think there must be something wrong, maybe it's my fault :)

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
Hi,

No it's not your fault, nor is it the plugin's. Other apps are hijacking the whatsapp scheme for image sharing, so those are to blame. Same happens when you try to share to Instagram.

**Comment by andreground** [comment]
Ahahah even Apple is doing that! What a shame :) Thanks btw :+1:
