### ISSUE TITLE
Resources cannot be located in AppBuilder Companion App

### ISSUE THREAD

**Issue by mbektchiev** [Telerik-Verified-Plugins/SocialSharing#6]
The reason is that paths starting with `www/` are treated as pointing to files located in the application package's assets. In the Companion App, however, all files of the deployed project are inside the internal `files` directory. 

A possible fix is to treat them as relative to the currently open app page. Its location will be inside the package on a publish build and in the `files` directory in the Companion and on debug builds.

Another approach is to treat all relative paths as such to the current page and leave `www` as it is. The sample will have to be changed and all current applications will have to be updated, in order to get the fix.

**Comment by EddyVerbruggen** [comment]
Hey Martin,

I'm trying to solve this but am wondering how I could test it in a Companion app context locally.. do you have a convenient way to do that? AFAIK I have no way to the Companion app repo so I can't run it locally..

Thanks!

**Comment by mbektchiev** [comment]
Here are the steps to reproduce:

* Clone https://github.com/Telerik-Verified-Plugins/SocialSharing-DemoApp in AppBuilder WebClient 
* Install AppBuilder Companion App on a device using this link: https://play.google.com/store/apps/details?id=com.telerik.AppBuilder&hl=en
* Build for companion app and scan the qrcode.

In the sample app:

* Press "Share multiple images on Facebook" or ''Share message and image on Facebook'

=> result: Alert SocialSharing error: www/styles/images/logo.png
The facebook post form opens but the images are not attached

**Comment by EddyVerbruggen** [comment]
Hey Martin, sorry that Q was unclear. I get how to reproduce it and I have a potential fix. But I'm looking for a way to test and debug the fix in a local project. So essentially cloning the companion app source etc. I've done it in the past with the PhoneGap dev app to test the Insomnia plugin.
