### ISSUE TITLE
Alter: plugin not found. maybe you are running in AppBuilder companion app which does not support this plugin

### ISSUE THREAD

**Issue by TarneemOmar** [Telerik-Verified-Plugins/SocialSharing#9]
Hi

I have downloaded the demo file and done the steps mentioned in this plugin of social sharing, I am using phonegap. 
when I test the app in my mobile i got the following alter whenever I click on any button to share:
Alter: plugin not found. maybe you are running in AppBuilder companion app which does not support this plugin

I have included cordova.js in index.html file, and included the socialsharing plugin in config.xml, but its not working at all.

My phone has android version 5.1.0

any suggestion?

**Comment by EddyVerbruggen** [comment]
You're running this as a standlone app right, not inside the companion app?

Please share your project with me and I will help you.

**Comment by TarneemOmar** [comment]
here is my project file:
https://www.mediafire.com/?88s73xjd35o4sbf

**Comment by TarneemOmar** [comment]
I would like to share my answer, actually, I was running this using phonegap on my phone which is not supporting running this plugin currently. when I connected my phone via USB and test it using Android Studio simulator, it works perfectly!!

Thanks for such a wonderful API :)

**Comment by mesqueeb** [comment]
@TarneemOmar you mean to say that there is a possibility that running on an iPhone via USB this plugin will not work?
